theme:
  name: material
  palette:
    scheme: slate
    primary: indigo

nav:
    - 'index.md'
    - 'getting-started.md'
    - 'dummy-data.md'
    - 'repeating-data.md'

site_name: http-response

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences