theme:
  name: material
  palette:
    scheme: slate
    primary: indigo

extra_css: [assets/styles.css]

repo_url: https://github.com/johannesss/http-response
repo_name: johannesss/http-response
edit_uri: /johannesss/http-response/edit/main/docs/docs

nav:
    - 'index.md'
    - 'getting-started.md'
    - 'fake-data.md'
    - 'repeating-data.md'

site_name: http-response

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences